# Generated by Django 4.1.3 on 2022-11-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='micropost',
            field=models.IntegerField(blank=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=15, verbose_name='名前'),
        ),
    ]
