# Generated by Django 4.1.3 on 2022-11-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0003_calc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='div',
        ),
        migrations.RemoveField(
            model_name='calc',
            name='mul',
        ),
        migrations.RemoveField(
            model_name='calc',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='calc',
            name='sum',
        ),
    ]
